import { Lab } from "../types/Lab";

export const labs: Lab[] = [
  {
    id: 1,
    title: "SQL Injection",
    category: "База данных",
    description: "Освойте техники SQL-инъекций для понимания безопасности баз данных",
    difficulty: "Новичок",
    duration: 20,
    xpReward: 100,
    completed: true,
    unlocked: true,
    briefing: "Обойдите авторизацию и получите доступ как admin",
    hint: "Попробуйте использовать SQL-комментарии (--) для игнорирования остальной части запроса",
    vulnerableCode: `SELECT * FROM users WHERE username='$username' AND password='$password';`,
    correctPayload: "admin' --",
    targetInfo: "MySQL 5.7"
  },
  {
    id: 2,
    title: "XSS Attack",
    category: "Веб-безопасность",
    description: "Изучите межсайтовый скриптинг и способы защиты",
    difficulty: "Новичок",
    duration: 25,
    xpReward: 150,
    completed: false,
    unlocked: true,
    briefing: "Выполните JavaScript код на странице без блокировки фильтров",
    hint: "Попробуйте обойти фильтры, используя разные методы экранирования",
    vulnerableCode: `<input type="text" value="$userInput" />`,
    correctPayload: `<script>alert(1)</script>`,
    targetInfo: "Chrome 120"
  },
  {
    id: 3,
    title: "Brute Force",
    category: "Аутентификация",
    description: "Изучите методы подбора паролей",
    difficulty: "Средний",
    duration: 30,
    xpReward: 200,
    completed: false,
    unlocked: true,
    briefing: "Подберите правильный пароль к аккаунту администратора",
    hint: "Используйте список часто используемых паролей",
    vulnerableCode: `if (username === "admin" && password === "password123") { return true; }`,
    correctPayload: "admin:password123",
    targetInfo: "Admin Panel"
  },
  {
    id: 4,
    title: "Command Injection",
    category: "Системная безопасность",
    description: "Научитесь находить уязвимости командной инъекции",
    difficulty: "Сложный",
    duration: 45,
    xpReward: 500,
    completed: false,
    unlocked: false,
    briefing: "Выполните системную команду через форму ввода",
    hint: "Используйте разделители команд (;) или операторы условия (&&, ||)",
    vulnerableCode: `os.system("ping " + userInput)`,
    correctPayload: `; ls`,
    targetInfo: "Linux Server"
  },
  {
    id: 5,
    title: "JWT Exploit",
    category: "Токены",
    description: "Изучите атаки на JWT",
    difficulty: "Эксперт",
    duration: 60,
    xpReward: 700,
    completed: false,
    unlocked: false,
    briefing: "Обойдите JWT токен и получите доступ к админ-панели",
    hint: "Проверьте алгоритм подписи и попробуйте подделать токен",
    vulnerableCode: `jwt.verify(token, 'secret-key', { algorithms: ['HS256', 'none'] })`,
    correctPayload: `eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhZG1pbiI6dHJ1ZX0.`,
    targetInfo: "JWT Auth"
  }
];